### ISSUE TITLE
Is this project still mantained?

### ISSUE THREAD

**Issue by fatshotty** [marcofranssen/socket.io-memcached#3]
Hello
is this package still mantained?

I need to handle socket.io with memcached and this package seems to be the solution :)

thanks in advance

**Comment by marcofranssen** [comment]
I'm not using it anymore, but it might still perfectly do the job. 

I'm open to PRs though if that helps.

**Comment by marcofranssen** [comment]
e.g.

- use yarn
- update dependencies
- add github actions

**Comment by fatshotty** [comment]
thanks for your reply ;)

**Comment by fatshotty** [comment]
I think my project will not use memcached anymore, because it will be rewritten using redis in next months.
Thank again for your reply ;)
